#!/usr/bin/env bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
# Get credentials key for ECR from AWS without using the full blown aws client
set -e

if [ -n "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
    SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
fi
source "$SCRIPT_DIR/aws-functions"


export src=""
export method="POST"
export service="ecr"
export host="${service}.${AWS_REGION}.amazonaws.com"
export x_amz_target="AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken"

export payload="{}"


curl --tcp-nodelay -qsfL -X ${method} --data "${payload}" \
  "https://${host}/${src}" \
  -H "Authorization: AWS4-HMAC-SHA256 Credential=${AWS_ACCESS_KEY_ID?}/${date_scope}/${AWS_REGION}/${service}/aws4_request,SignedHeaders=$(all_signed_headers),Signature=$(signature)" \
  -H "Accept-Encoding: identity" \
  -H "Content-Type: application/x-amz-json-1.1" \
  -H "Date: ${date_header}" \
  -H "x-amz-content-sha256: $(payload_hash)" \
  -H "x-amz-date: ${iso_timestamp}" \
  -H "x-amz-target: ${x_amz_target}" \
  $*
