#!/usr/bin/env bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
# Return a docker login line
set +e

if [ -n "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
    SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
fi
source "$SCRIPT_DIR/aws-functions"

ECR_GET_AUTHORIZATION_TOKEN="$SCRIPT_DIR/ecr-get-authorization-token"
if [ ! -x "$ECR_GET_AUTHORIZATION_TOKEN" ]; then
    ECR_GET_AUTHORIZATION_TOKEN="/usr/local/bin/ecr-get-authorization-token"
fi
if [ ! -x "$ECR_GET_AUTHORIZATION_TOKEN" ]; then
    ECR_GET_AUTHORIZATION_TOKEN="./ecr-get-authorization-token"
fi
if [ ! -x "$ECR_GET_AUTHORIZATION_TOKEN" ]; then
    ECR_GET_AUTHORIZATION_TOKEN="ecr-get-authorization-token"
fi

set -e
data=$("$ECR_GET_AUTHORIZATION_TOKEN")
token="$(echo "$data" | jq -r '.authorizationData[0].authorizationToken' | $OPENSSL base64 -d)"
export ECR_USERNAME=$(echo "$token" | cut -d: -f1)
export ECR_PASSWORD=$(echo "$token" | cut -d: -f2-)
export ECR_REGISTRY=$(echo "$data" | jq '.authorizationData[0].proxyEndpoint')

echo "docker login -u $ECR_USERNAME -p $ECR_PASSWORD $ECR_REGISTRY"