#!/usr/bin/env bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
# Download a file from S3
set -e

if [ -n "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
    SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
fi
source "$SCRIPT_DIR/aws-functions"

export bucket="${1}"; shift
export src="${1}"; shift
export method="GET"
export service="s3"
export host="${bucket}.${service}.amazonaws.com"
export x_amz_target=""

export payload=""


curl --tcp-nodelay -qsfL -X ${method} --data "${payload}" \
  "https://${host}/${src}" \
  -H "Authorization: AWS4-HMAC-SHA256 Credential=${AWS_ACCESS_KEY_ID?}/${date_scope}/${AWS_REGION}/${service}/aws4_request,SignedHeaders=$(all_signed_headers),Signature=$(signature)" \
  -H "Date: ${date_header}" \
  -H "x-amz-content-sha256: $(payload_hash)" \
  -H "x-amz-date: ${iso_timestamp}" \
  $*
